# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '500px Mobile Challenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :ios, '10.0'
  use_frameworks!

  # Pods for 500px Mobile Challenge
  pod 'Alamofire'
  pod 'OAuthSwift'

  target '500px Mobile ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '500px Mobile ChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
